//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumberCorp.Pages {
	
	
	public partial class Contacts {
		
		protected System.Web.UI.WebControls.Content FeaturedContent;
		
		protected System.Web.UI.WebControls.Content MainContent;
		
		protected LumberCorp.StockControl stockControl;
		
		protected LumberCorp.AdminControl adminControl1;
	}
}
